# use_frameworks!
platform :ios, '8.0'

target 'PubPodDemo_Example' do
  pod 'PubPodDemo', :path => '../'

  target 'PubPodDemo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
